### ISSUE TITLE
Maybe you have used the val and test data in training stage

### ISSUE THREAD

**Issue by HuShaohanAI** [lichengunc/MAttNet#11]
Hi~
I have found that in your "sample_neg_ids" function, the code "neg_ref_id = random.choice(self.Refs.keys())", you random choose a ref as a neg_ref, so you have used the val or test ref data in your training stage

**Comment by lichengunc** [comment]
Hi, you are right here! 
Sorry for this bug, but this test/val leaking problem rarely occurs if you check the "if...else" conditions. I also have a correct dataloader with strict split at hand (not released), the performance remains unchanged. 

I might leave it for now as it won't change the performance, but feel free to revise it to be "self.training_ref_ids" :-) Thanks.
