### ISSUE TITLE
Demo website not working

### ISSUE THREAD

**Issue by mees** [lichengunc/MAttNet#12]
Hi,
the demo website appears to be down
http://vision2.cs.unc.edu/refer/comprehension
could you check it please?

**Comment by lichengunc** [comment]
I intentionally shut it down for the coming CVPR deadline (we are running out of gpus). It will be recovered in a few days (early next week). Thanks for your interest.

**Comment by lichengunc** [comment]
Back now.

**Comment by mees** [comment]
The demo is online and works with the predefined images, but it throws an error when you try to upload an image 'server error 500'.

**Comment by lichengunc** [comment]
Fixed :-) Thanks for the remind.

**Comment by mees** [comment]
Quick question, which pretrained model is running on the web demo?

**Comment by mees** [comment]
Cool! Do you plan on releasing that model and/or instructions to train it?
I am interested in knowing how you combine visual genome since there are no
segmentation masks there.

**Comment by lichengunc** [comment]
Hm..we don't have plan to release the demo model.
As for the Genome data, we use the 80 COCO categories appeared in Visual Genome, thus it is still 80 COCO categories. Our training are now with more (also noisy) data (as Genome's expressions are not strictly referring expressions). For some categories, this strategy is helping.

**Comment by mees** [comment]
I see, but are there gt masks for the 80 coco classes on the visual genome
dataset?  I think that some images of visual genome are part of coco, but I
am not sure. Where can one see the split of visual genome that has gt mask
data?

**Comment by Shivanshmundra** [comment]
Hey, Website is still not working. Can you check it please?
