### ISSUE TITLE
Can you explain what's head_feats and ann_feats?

### ISSUE THREAD

**Issue by yangshao** [lichengunc/MAttNet#21]
Can you explain what are the difference between these two features?

**Comment by lichengunc** [comment]
head_feats are the images' convolutional outputs and ann_feats are the regions' pooled features.

**Comment by yangshao** [comment]
@lichengunc Thanks for your reply. For the ann_feats, are they specified or auto detected?

**Comment by lichengunc** [comment]
These are regional pooled features. Yes, ROI features are the cropped features, whose pooling is the ann_feats.

**Comment by yangshao** [comment]
@lichengunc I think i don't describe my question clearly. During the training,  the ground-truth bounding boxes are given, while during the testing, the bounding boxes are detected. Where is the code to get the ground-truth bounding box regional features? Thanks!

**Comment by lichengunc** [comment]
Please go check: https://github.com/lichengunc/MAttNet#training
