### ISSUE TITLE
ImportError: No module named _mask

### ISSUE THREAD

**Issue by yangshao** [lichengunc/MAttNet#22]
I try to make the rcnn work. When I  execute "python tools/make_coco_minus_refer_instances.py
", I have this error. and the python path is okay.  I don't see any file "_mask.py" under the folder data/refer/external/, but only _mask.pyx.  What's the _mask?

**Comment by lichengunc** [comment]
Each dependency needs some setup. Please check carefully https://github.com/lichengunc/refer and https://github.com/lichengunc/mask-faster-rcnn for more details. 
For this error, I guess you need to do ``make" in the refer repo.

**Comment by yangshao** [comment]
thanks. it is. I think it would be better to add this under the mask-faster-rcnn project readme...
