### ISSUE TITLE
Out of Memory Error: run_detect.py

### ISSUE THREAD

**Issue by abdullahjamal** [lichengunc/MAttNet#25]
I'm trying to execute run_detect.py file but it's taking more than 12GB memory on a single GPU. That occurs around 13500 image out of 19994. What could be the possible reason?

**Comment by abdullahjamal** [comment]
Issue solved, I'm using an older version of Pytorch, so just need to delete gpu cache memory.

**Comment by dami23** [comment]
Hi, ABdullah. I also encounter this error. Could you please share your resolution? Thank you!!

**Comment by abdullahjamal** [comment]
Hi dami,

I used torch.cuda.empty_cache() after the inference of the detections, or you can even delete scores and boxes by del scores; del boxes after you're done saving it for a single image.

**Comment by dami23** [comment]
Sincerely thank you for your reply, ABdullah!!!
