### ISSUE TITLE
Error when running training step 2

### ISSUE THREAD

**Issue by roger60229** [lichengunc/MAttNet#26]
Hi,
I get the error message when i run the command "CUDA_VISIBLE_DEVICES=gpu_id python tools/extract_mrcn_head_feats.py --dataset refcoco --splitBy unc".

RuntimeError: While copying the parameter named rpn_cls_score_net.weight, whose dimensions in the model are torch.Size([18, 512, 1, 1]) and whose dimensions in the checkpoint are torch.Size([24, 512, 1, 1])

I'm running under python2.7, pytorch 0.3.1, CUDA 9.

Can someone help me to figure out the problem?

Thx

**Comment by roger60229** [comment]
Solved after reconstruct the pytorch envs. Thx :)

**Comment by cuienjiecv** [comment]
@roger60229  Hello, can you run this code to succeed? I run a lot of bugs in running the code.
