### ISSUE TITLE
encountered an error when "runipy cv/mrcn_detection.ipynb"

### ISSUE THREAD

**Issue by PGodzilla** [lichengunc/MAttNet#3]
04/28/2018 07:57:41 PM INFO: Cell raised uncaught exception: 
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-2-fcc8de952d8f> in <module>()
      6 parser.add_argument('--tag', default='notime')
      7 args = parser.parse_args('')
----> 8 mrcn = inference.Inference(args)
      9 imdb = mrcn.imdb

/home/pengjun/MAttNet/MAttNet/lib/mrcn/inference.pyc in __init__(self, args)
     63 
     64     # Load network
---> 65     self.net = self.load_net()
     66 
     67   def load_net(self):

/home/pengjun/MAttNet/MAttNet/lib/mrcn/inference.pyc in load_net(self)
     83     model = osp.join(mrcn_dir, 'output/%s/%s/%s/%s_mask_rcnn_iter_%s.pth' % \
     84       (self.net_name, get_imdb_name(self.imdb_name)['TRAIN_IMDB'], self.tag, self.net_name, self.iters))
---> 85     assert osp.isfile(model)
     86     net.load_state_dict(torch.load(model))
     87     print('pretrained-model loaded from [%s].' % model)

AssertionError: 
04/28/2018 07:57:41 PM INFO: Shutdown kernel
04/28/2018 07:57:42 PM WARNING: Exiting with nonzero exit status

**Comment by lichengunc** [comment]
Please follow the instructions of my mask-faster-rcnn repo (https://github.com/lichengunc/mask-faster-rcnn), preparing everything needed for pyutils/mask-faster-rcnn. 
Then use cv/mrcn_detection.ipynb to check if you've get Mask R-CNN ready for MattNet Repo.

**Comment by PGodzilla** [comment]
It has been solved, thanks for your reply!

**Comment by cuienjiecv** [comment]
@PGodzilla Hello, can you run this code to succeed? I run a lot of bugs in running the code.
