### ISSUE TITLE
RuntimeError: dimension out of range

### ISSUE THREAD

**Issue by shujon** [lichengunc/MAttNet#4]
Hi 
I am getting the following error while running CUDA_VISIBLE_DEVICES=1 python tools/extract_mrcn_ann_feats.py --dataset refcoco --splitBy unc

Traceback (most recent call last):
  File "tools/extract_mrcn_ann_feats.py", line 143, in <module>
    main(args)
  File "tools/extract_mrcn_ann_feats.py", line 121, in main
    ann_pool5, ann_fc7 = ann_to_pool5_fc7(mrcn, ann, net_conv, im_info)
  File "tools/extract_mrcn_ann_feats.py", line 74, in ann_to_pool5_fc7
    fc7 = fc7.mean(3).mean(2)
RuntimeError: dimension out of range (expected to be in range of [-2, 1], but got 3)

Can you please help me to figure out the issue?

**Comment by lichengunc** [comment]
I feel this is mainly due to the pytorch version. - my pytorch was 0.2 for this repo.

**Comment by lichengunc** [comment]
Fixed.
