### ISSUE TITLE
The accuracy of the verification set is lower than that of the original paper

### ISSUE THREAD

**Issue by almumujin** [lichengunc/MAttNet#41]
Hi,
  I run the refcoco dataset with gt_boxes，but the val_acc is 78%.（I'm using python3）

**Comment by sduzpp** [comment]
> Hi, I run the refcoco dataset with gt_boxes，but the val_acc is 78%.（I'm using python3）

Have you run the code yet? What is the specific version of the environment you configured? Thanks you!
